### ISSUE TITLE
一点就闪退。。

### ISSUE THREAD

**Issue by sz1900599168** [Pix-00/HoUnits#1]
![Screenshot_2020-09-26-22-00-05-530_com android settings](https://user-images.githubusercontent.com/33706513/94342477-d4ec5900-0043-11eb-8e83-0fd310e3a36a.jpg)
安卓版本：10

**Comment by Pix-00** [comment]
唔 我觉得不是Android 10的问题
我的手机（物理机也是10）测试没问题倒是。。。
试试新release看看 要是还有问题我觉得就是指令集的问题了
https://github.com/Pix-00/HoUnits/releases/tag/v1.2.1-fix

**Comment by sz1900599168** [comment]
现在不闪退了。不过软件方面有个建议，g/mol这的摩尔质量可以考虑改成下拉框选择性激素六项里的摩尔质量，比如 戊酸雌二醇的摩尔质量是272.38，可以在下拉框里快速选择。不然，每次换算都得百度查下分子量。。
![Screenshot_2020-11-26-13-27-52-398_com passionfruit HoUnits](https://user-images.githubusercontent.com/33706513/100312137-68aeb700-2fec-11eb-96b9-1f2e5e69ce3b.jpg)
